from fastapi import APIRouter, Depends, HTTPException, Response
from sqlalchemy.ext.asyncio import AsyncSession
from app.database import get_db
from app.models.user import User, UserRole
from app.routes.auth import get_current_user
import csv
import io
from datetime import datetime

router = APIRouter(prefix="/reports", tags=["reports"])

@router.get("/senior/download")
async def download_senior_report(db: AsyncSession = Depends(get_db), current_user: User = Depends(get_current_user)):
    """Generate and download a comprehensive CSV report for senior executives"""
    
    if current_user.role != UserRole.SENIOR:
        raise HTTPException(status_code=403, detail="Access denied")
    
    # In a real app, this would aggregate data from various sources
    # For now, we'll generate a mock CSV structure matching the requirement
    
    output = io.StringIO()
    writer = csv.writer(output)
    
    # Write Header
    writer.writerow(["Report Generated At", datetime.utcnow().isoformat()])
    writer.writerow(["Generated By", current_user.full_name])
    writer.writerow([])
    
    # Section 1: Organization Stats
    writer.writerow(["--- ORGANIZATION STATS ---"])
    writer.writerow(["Metric", "Value"])
    writer.writerow(["Operational Efficiency", "87.5%"])
    writer.writerow(["Compliance Rate", "92.3%"])
    writer.writerow(["Escalated Concerns", "3"])
    writer.writerow([])
    
    # Section 2: Compliance Data (Mock)
    writer.writerow(["--- COMPLIANCE DATA ---"])
    writer.writerow(["Policy Name", "Completion %", "Status"])
    writer.writerow(["Data Security 2024", "95%", "High"])
    writer.writerow(["Remote Work Policy", "88%", "Normal"])
    writer.writerow(["Code of Conduct", "100%", "High"])
    writer.writerow([])
    
    # Section 3: Workforce Summary (Mock)
    writer.writerow(["--- WORKFORCE SUMMARY ---"])
    writer.writerow(["Department", "Headcount", "Overutilized"])
    writer.writerow(["Engineering", "45", "5"])
    writer.writerow(["Sales", "30", "2"])
    writer.writerow(["HR", "10", "0"])
    
    output.seek(0)
    
    headers = {
        'Content-Disposition': f'attachment; filename="executive_report_{datetime.now().strftime("%Y%m%d")}.csv"',
        'Content-Type': 'text/csv'
    }
    
    return Response(content=output.getvalue(), headers=headers, media_type="text/csv")
